In [1]:
# Copyright 2023, Acadential, All rights reserved.

# 2-5. PyTorch 기초 - Tensor

## Tensor란?

Tensor란 데이터를 표현하는 단위로, 다차원 배열의 일반화된 모습입니다. \
PyTorch에서 Tensor을 가지고 연산을 수행하면, 해당 연산은 Computational Graph 상에 표현되고, 나중에 Backward propagation을 통해 Gradient를 계산할 수 있습니다.

## Initializing a tensor

Tensor을 정의하는 방법은 다음과 같습니다.

1. 지정된 값으로 초기화
2. 랜덤한 값으로 초기화
3. Numpy array로부터 초기화

In [4]:
# Import related library
import numpy as np 
import torch 

## 초기화 방법 1: 지정된 값으로 Tensor 초기화

In [5]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

In [6]:
x_data

tensor([[1, 2],
        [3, 4]])

In [5]:
x_data.dtype  # data type is automatically inferred

torch.int64

## 초기화 방법 2: 랜덤한 값으로 Tensor 초기화

In [7]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.7572, 0.2368, 0.6388],
        [0.1771, 0.1275, 0.3258]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


## 초기화 방법 3: Numpy 배열로부터 Tensor 초기화

In [8]:
data = [[1, 2],[3, 4]]
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [8]:
x_np

tensor([[1, 2],
        [3, 4]])

In [9]:
x_np.dtype

torch.int64

# Tensor 데이터의 형식 지정

Tensor의 데이터 형식은 어떤 것들이 있을까요?

1. 정수 int (integer) \
    1-1. ```torch.int8```, ```torch.int16```, ```torch.int32```, ```torch.int64``` (```torch.long```) \
    1-2. ```torch.uint8```: unsigned integer로 양의 정수 0 ~ 255 숫자만 포함, 주로 이미지 데이터를 다룰 때 사용.
2. float \
    2-1. ```torch.float16```, ```torch.float32```, ```torch.float64``` 
3. boolean: ```torch.bool```
4. etc.



### torch.float32 형식으로 초기화

In [10]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data, dtype=torch.float32)

In [11]:
x_data

tensor([[1., 2.],
        [3., 4.]])

In [12]:
x_data.dtype

torch.float32

### torch.uint8 형식으로 초기화

In [13]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data, dtype=torch.uint8)

In [14]:
x_data

tensor([[1, 2],
        [3, 4]], dtype=torch.uint8)

### 다른 dtype으로 변환

In [15]:
x_data = x_data.to(torch.float16)

In [16]:
x_data.dtype

torch.float16

# 다른 Device로 Tensor 옮기기

1. GPU가 사용가능한지 확인하기
2. 다른 Device로 Tensor 옮기기
3. 어떤 Device상에 Tensor가 있는지 확인하기

### GPU가 사용가능한지 확인하기

In [11]:
torch.cuda.is_available()

False

### GPU로 Tensor 옮기기

In [13]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

### CPU로 Tensor 옮기기

In [19]:
x_data = x_data.cpu()

### 어떤 Device상에 Tensor가 있는지 확인하기

In [14]:
x_data.device

device(type='cpu')

# Tensor을 활용한 연산

1. Indexing and slicing
2. Concatenation
3. Arithmetric
4. Inplace-operation

### Indexing 

In [15]:
tensor = torch.ones(4, 4)

In [16]:
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


### Concatenation

In [29]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[6., 5., 6., 6., 6., 5., 6., 6., 6., 5., 6., 6.],
        [6., 5., 6., 6., 6., 5., 6., 6., 6., 5., 6., 6.],
        [6., 5., 6., 6., 6., 5., 6., 6., 6., 5., 6., 6.],
        [6., 5., 6., 6., 6., 5., 6., 6., 6., 5., 6., 6.]])


### Arithmetric

In [26]:
# 행렬의 곱
y1 = tensor @ tensor.T  # .T는 transpose
y2 = tensor.matmul(tensor.T)
# print(y1)
# print(y2)

In [27]:
# Element-wise 곱셈
z1 = tensor * tensor
z2 = tensor.mul(tensor)
print(z1)
print(z2)

tensor([[36., 25., 36., 36.],
        [36., 25., 36., 36.],
        [36., 25., 36., 36.],
        [36., 25., 36., 36.]])
tensor([[36., 25., 36., 36.],
        [36., 25., 36., 36.],
        [36., 25., 36., 36.],
        [36., 25., 36., 36.]])


### Inplace operation

In [33]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[21., 20., 21., 21.],
        [21., 20., 21., 21.],
        [21., 20., 21., 21.],
        [21., 20., 21., 21.]]) 

tensor([[26., 25., 26., 26.],
        [26., 25., 26., 26.],
        [26., 25., 26., 26.],
        [26., 25., 26., 26.]])
